version: "3.7"
services:

    app:
        build:
            args:
                user: test
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: test
        container_name: application-container
        restart: unless-stopped
        working_dir: /var/www/html
        ports:
            -   "8000:8080"
        networks:
            - testnet

    database:
        image: mariadb:10.6
        container_name: database-container
        restart: unless-stopped
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: test
            MYSQL_USER: test
            MYSQL_PASSWORD: toor
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - testnet

networks:
    testnet:
        driver: bridge
